2025-05-05 22:58:51,749 INFO main Shutting Down!
2025-05-05 23:01:40,092 INFO main Server ready!
2025-05-05 23:13:35,094 INFO main Shutting Down!
2025-05-05 23:17:09,091 INFO main Server ready!
2025-05-05 23:30:09,876 INFO main Shutting Down!
2025-05-05 23:30:11,597 INFO main Server ready!
2025-05-05 23:32:49,800 INFO main Shutting Down!
2025-05-05 23:32:51,399 INFO main Server ready!
2025-05-05 23:36:04,935 INFO main {'visit_id': 1234, 'exposure_start_mjd': 60641.04957530673, 'exposure_end_mjd': 60641.049922528946, 'boresight_ra': 38.3951559125, 'boresight_dec': 7.1126590888}
2025-05-05 23:36:05,027 INFO web_log 127.0.0.1 [05/May/2025:15:36:04 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:36:05,027 INFO web_log 127.0.0.1 [05/May/2025:15:36:04 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:36:05,030 INFO main {}
2025-05-05 23:36:05,030 INFO web_log 127.0.0.1 [05/May/2025:15:36:05 -0800] "GET /visit_cache HTTP/1.1" 200 398 "-" "python-requests/2.32.3"
2025-05-05 23:36:05,030 INFO web_log 127.0.0.1 [05/May/2025:15:36:05 -0800] "GET /visit_cache HTTP/1.1" 200 398 "-" "python-requests/2.32.3"
2025-05-05 23:36:05,032 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:36:05,033 INFO web_log 127.0.0.1 [05/May/2025:15:36:05 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:36:05,033 INFO web_log 127.0.0.1 [05/May/2025:15:36:05 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:36:05,035 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:36:05,036 INFO web_log 127.0.0.1 [05/May/2025:15:36:05 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:36:05,036 INFO web_log 127.0.0.1 [05/May/2025:15:36:05 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:47:41,148 INFO main Shutting Down!
2025-05-05 23:47:42,849 INFO main Server ready!
2025-05-05 23:47:44,869 INFO main {'visit_id': 1234, 'exposure_start_mjd': 60641.04957530673, 'exposure_end_mjd': 60641.049922528946, 'boresight_ra': 38.3951559125, 'boresight_dec': 7.1126590888}
2025-05-05 23:47:44,945 INFO web_log 127.0.0.1 [05/May/2025:15:47:44 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:47:44,945 INFO web_log 127.0.0.1 [05/May/2025:15:47:44 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:47:44,947 INFO main {}
2025-05-05 23:47:44,947 INFO web_log 127.0.0.1 [05/May/2025:15:47:44 -0800] "GET /visit_cache HTTP/1.1" 200 397 "-" "python-requests/2.32.3"
2025-05-05 23:47:44,947 INFO web_log 127.0.0.1 [05/May/2025:15:47:44 -0800] "GET /visit_cache HTTP/1.1" 200 397 "-" "python-requests/2.32.3"
2025-05-05 23:47:44,949 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:47:44,949 ERROR sattlePy Error in SattleFilterTask.run: 'dict' object has no attribute 'shape'
2025-05-05 23:47:44,949 ERROR main Failed to filter diasources: 'dict' object has no attribute 'shape'
Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 239, in run
    if sat_coords.shape[0] != 2:
       ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/app/main.py", line 316, in diasource_handler
    allow_list = sattleFilterTask.run(cache[visit_id], data['diasources'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 268, in run
    raise RuntimeError(f"Failed to filter diasources: {str(e)}")
RuntimeError: Failed to filter diasources: 'dict' object has no attribute 'shape'
2025-05-05 23:47:44,949 INFO web_log 127.0.0.1 [05/May/2025:15:47:44 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:47:44,949 INFO web_log 127.0.0.1 [05/May/2025:15:47:44 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:47:44,950 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:47:44,950 ERROR sattlePy Error in SattleFilterTask.run: 'dict' object has no attribute 'shape'
2025-05-05 23:47:44,950 ERROR main Failed to filter diasources: 'dict' object has no attribute 'shape'
Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 239, in run
    if sat_coords.shape[0] != 2:
       ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/app/main.py", line 316, in diasource_handler
    allow_list = sattleFilterTask.run(cache[visit_id], data['diasources'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 268, in run
    raise RuntimeError(f"Failed to filter diasources: {str(e)}")
RuntimeError: Failed to filter diasources: 'dict' object has no attribute 'shape'
2025-05-05 23:47:44,951 INFO web_log 127.0.0.1 [05/May/2025:15:47:44 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:47:44,951 INFO web_log 127.0.0.1 [05/May/2025:15:47:44 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:47:49,580 INFO main {'visit_id': 1234, 'exposure_start_mjd': 60641.04957530673, 'exposure_end_mjd': 60641.049922528946, 'boresight_ra': 38.3951559125, 'boresight_dec': 7.1126590888}
2025-05-05 23:47:49,580 INFO web_log 127.0.0.1 [05/May/2025:15:47:49 -0800] "PUT /visit_cache HTTP/1.1" 200 180 "-" "python-requests/2.32.3"
2025-05-05 23:47:49,580 INFO web_log 127.0.0.1 [05/May/2025:15:47:49 -0800] "PUT /visit_cache HTTP/1.1" 200 180 "-" "python-requests/2.32.3"
2025-05-05 23:47:49,582 INFO main {}
2025-05-05 23:47:49,582 INFO web_log 127.0.0.1 [05/May/2025:15:47:49 -0800] "GET /visit_cache HTTP/1.1" 200 397 "-" "python-requests/2.32.3"
2025-05-05 23:47:49,582 INFO web_log 127.0.0.1 [05/May/2025:15:47:49 -0800] "GET /visit_cache HTTP/1.1" 200 397 "-" "python-requests/2.32.3"
2025-05-05 23:47:49,583 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:47:49,583 ERROR sattlePy Error in SattleFilterTask.run: 'dict' object has no attribute 'shape'
2025-05-05 23:47:49,583 ERROR main Failed to filter diasources: 'dict' object has no attribute 'shape'
Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 239, in run
    if sat_coords.shape[0] != 2:
       ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/app/main.py", line 316, in diasource_handler
    allow_list = sattleFilterTask.run(cache[visit_id], data['diasources'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 268, in run
    raise RuntimeError(f"Failed to filter diasources: {str(e)}")
RuntimeError: Failed to filter diasources: 'dict' object has no attribute 'shape'
2025-05-05 23:47:49,583 INFO web_log 127.0.0.1 [05/May/2025:15:47:49 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:47:49,583 INFO web_log 127.0.0.1 [05/May/2025:15:47:49 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:47:49,585 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:47:49,585 ERROR sattlePy Error in SattleFilterTask.run: 'dict' object has no attribute 'shape'
2025-05-05 23:47:49,585 ERROR main Failed to filter diasources: 'dict' object has no attribute 'shape'
Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 239, in run
    if sat_coords.shape[0] != 2:
       ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/app/main.py", line 316, in diasource_handler
    allow_list = sattleFilterTask.run(cache[visit_id], data['diasources'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 268, in run
    raise RuntimeError(f"Failed to filter diasources: {str(e)}")
RuntimeError: Failed to filter diasources: 'dict' object has no attribute 'shape'
2025-05-05 23:47:49,585 INFO web_log 127.0.0.1 [05/May/2025:15:47:49 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:47:49,585 INFO web_log 127.0.0.1 [05/May/2025:15:47:49 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:53:07,439 INFO main Shutting Down!
2025-05-05 23:53:10,413 INFO main Server ready!
2025-05-05 23:53:12,179 INFO main {'visit_id': 1234, 'exposure_start_mjd': 60641.04957530673, 'exposure_end_mjd': 60641.049922528946, 'boresight_ra': 38.3951559125, 'boresight_dec': 7.1126590888}
2025-05-05 23:53:12,253 INFO web_log 127.0.0.1 [05/May/2025:15:53:12 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:53:12,253 INFO web_log 127.0.0.1 [05/May/2025:15:53:12 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:53:12,255 INFO main {}
2025-05-05 23:53:12,255 INFO web_log 127.0.0.1 [05/May/2025:15:53:12 -0800] "GET /visit_cache HTTP/1.1" 200 396 "-" "python-requests/2.32.3"
2025-05-05 23:53:12,255 INFO web_log 127.0.0.1 [05/May/2025:15:53:12 -0800] "GET /visit_cache HTTP/1.1" 200 396 "-" "python-requests/2.32.3"
2025-05-05 23:53:12,256 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:53:12,257 INFO web_log 127.0.0.1 [05/May/2025:15:53:12 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:53:12,257 INFO web_log 127.0.0.1 [05/May/2025:15:53:12 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:53:12,258 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:53:12,258 INFO web_log 127.0.0.1 [05/May/2025:15:53:12 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:53:12,258 INFO web_log 127.0.0.1 [05/May/2025:15:53:12 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:55:40,725 INFO main Shutting Down!
2025-05-05 23:55:42,354 INFO main Server ready!
2025-05-05 23:55:45,441 INFO main {'visit_id': 1234, 'exposure_start_mjd': 60641.04957530673, 'exposure_end_mjd': 60641.049922528946, 'boresight_ra': 38.3951559125, 'boresight_dec': 7.1126590888}
2025-05-05 23:55:45,510 INFO web_log 127.0.0.1 [05/May/2025:15:55:45 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:55:45,510 INFO web_log 127.0.0.1 [05/May/2025:15:55:45 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:55:45,511 INFO main {}
2025-05-05 23:55:45,511 INFO web_log 127.0.0.1 [05/May/2025:15:55:45 -0800] "GET /visit_cache HTTP/1.1" 200 397 "-" "python-requests/2.32.3"
2025-05-05 23:55:45,511 INFO web_log 127.0.0.1 [05/May/2025:15:55:45 -0800] "GET /visit_cache HTTP/1.1" 200 397 "-" "python-requests/2.32.3"
2025-05-05 23:55:45,513 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:55:45,513 ERROR sattlePy Error in SattleFilterTask.run: list indices must be integers or slices, not str
2025-05-05 23:55:45,513 ERROR main Failed to filter diasources: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 240, in run
    source_bboxes = np.asarray(diaSources['bboxes'])
                               ~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/app/main.py", line 316, in diasource_handler
    allow_list = sattleFilterTask.run(cache[visit_id], data['diasources'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 258, in run
    raise RuntimeError(f"Failed to filter diasources: {str(e)}")
RuntimeError: Failed to filter diasources: list indices must be integers or slices, not str
2025-05-05 23:55:45,513 INFO web_log 127.0.0.1 [05/May/2025:15:55:45 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:55:45,513 INFO web_log 127.0.0.1 [05/May/2025:15:55:45 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:55:45,514 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:55:45,514 ERROR sattlePy Error in SattleFilterTask.run: list indices must be integers or slices, not str
2025-05-05 23:55:45,515 ERROR main Failed to filter diasources: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 240, in run
    source_bboxes = np.asarray(diaSources['bboxes'])
                               ~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/app/main.py", line 316, in diasource_handler
    allow_list = sattleFilterTask.run(cache[visit_id], data['diasources'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bsmart/LSST/code/sattle/python/lsst/sattle/sattlePy.py", line 258, in run
    raise RuntimeError(f"Failed to filter diasources: {str(e)}")
RuntimeError: Failed to filter diasources: list indices must be integers or slices, not str
2025-05-05 23:55:45,515 INFO web_log 127.0.0.1 [05/May/2025:15:55:45 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:55:45,515 INFO web_log 127.0.0.1 [05/May/2025:15:55:45 -0800] "PUT /diasource_allow_list HTTP/1.1" 400 217 "-" "python-requests/2.32.3"
2025-05-05 23:57:05,039 INFO main Shutting Down!
2025-05-05 23:57:06,542 INFO main Server ready!
2025-05-05 23:57:08,457 INFO main {'visit_id': 1234, 'exposure_start_mjd': 60641.04957530673, 'exposure_end_mjd': 60641.049922528946, 'boresight_ra': 38.3951559125, 'boresight_dec': 7.1126590888}
2025-05-05 23:57:08,532 INFO web_log 127.0.0.1 [05/May/2025:15:57:08 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:57:08,532 INFO web_log 127.0.0.1 [05/May/2025:15:57:08 -0800] "PUT /visit_cache HTTP/1.1" 200 199 "-" "python-requests/2.32.3"
2025-05-05 23:57:08,534 INFO main {}
2025-05-05 23:57:08,534 INFO web_log 127.0.0.1 [05/May/2025:15:57:08 -0800] "GET /visit_cache HTTP/1.1" 200 396 "-" "python-requests/2.32.3"
2025-05-05 23:57:08,534 INFO web_log 127.0.0.1 [05/May/2025:15:57:08 -0800] "GET /visit_cache HTTP/1.1" 200 396 "-" "python-requests/2.32.3"
2025-05-05 23:57:08,535 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:57:08,536 INFO web_log 127.0.0.1 [05/May/2025:15:57:08 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:57:08,536 INFO web_log 127.0.0.1 [05/May/2025:15:57:08 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:57:08,538 INFO main {'visit_id': 1234, 'detector_id': 8, 'diasources': [{'diasource_id': 4567, 'bbox': [[180.0, -23.1], [180.1, -23.1], [180.0, -23.0], [180.1, -23.0]]}, {'diasource_id': 4568, 'bbox': [[110, 34], [110, 30], [117, 34], [117, 30]]}]}
2025-05-05 23:57:08,538 INFO web_log 127.0.0.1 [05/May/2025:15:57:08 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
2025-05-05 23:57:08,538 INFO web_log 127.0.0.1 [05/May/2025:15:57:08 -0800] "PUT /diasource_allow_list HTTP/1.1" 200 224 "-" "python-requests/2.32.3"
